require("plugins.colorscheme")
require("plugins.oil")
require("plugins.git")
require("plugins.lualine")
require("plugins.mini")
require("plugins.tiny")
require("plugins.fidget")
require("plugins.lsp")
require("plugins.blink")
-- require("plugins.conform")
require("plugins.testing")
require("plugins.trouble")
